# 広告候補ゾーンのサイズ (幅[ピクセル], 高さ[ピクセル])
CANDIDATE_ZONE_SIZES = [[200, 300], [250, 350], [400, 500], [150, 200]]
# CANDIDATE_ZONE_SIZES = [[1000, 1000]]  # 該当広告が存在しない場合 (204 の場合をチェックするための設定)

# 広告サイズの ID リスト
ADS_SIZE_IDS = list(range(1, len(CANDIDATE_ZONE_SIZES) + 1))


PROHIBIT_STRINGS = [
    "ABC",
    "BCode",
    "Code",
    "ode1",
    "de12",
    "e123",
    "123",
    "23X",
    "3XY",
    "XYZ",
    "YZW",
    "ZWe",
    "Web",
    "WebService",
    "Service",
    "viceX",
    "iceXY",
    "ceXYZ",
    "eXYZ4",
    "XYZ4",
    "YZ45",
    "Z456",
    "456",
    "56D",
    "6Da",
    "Data",
    "DataStream",
    "Stream",
    "eamA",
    "amAB",
    "mABC",
    "ABCX",
    "BCXY",
    "CXYZ",
    "XYZ7",
    "YZ78",
    "Z789",
    "789",
    "89F",
    "9Fi",
    "Final",
    "FinalCode",
    "nalCode",
    "alCodeX",
    "lCodeXY",
    "CodeXYZ",
    "odeXYZ0",
    "deXYZ00",
    "eXYZ000",
    "XYZ0",
    "XYZ00",
    "XYZ000",
    "YZ0",
    "Z00",
    "000",
    "00E",
    "0En",
    "End",
    "ndX",
    "dXY",
    "Code123",
    "ServiceXYZ456",
    "StreamABCXYZ7",
    "FinalCodeXYZ000",
    "000End",
    "ABCode123XYZWeb",
    "DataStreamABCXYZ789Final",
]
